name: Scala Steward

on:
  schedule:
    # Minute         0…59
    # Stunde         0…23
    # Tag des Monats 1…31
    # Monat          1…12 (oder englische Namen, siehe unten)
    # Tag der Woche  0…7 (0 oder 7 ist Son, oder verwenden Sie englische Namen)
    - cron: "30 3 * * *"
  # Provide support for manually triggering the workflow via GitHub.
  workflow_dispatch:

jobs:
  scala-steward:
    name: scala-steward
    runs-on: ubuntu-latest
    steps:
      # This is necessary to ensure that the most up-to-date version of
      # REPOSITORIES.md is used.
      - uses: actions/checkout@v2

      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # A GitHub personal access token tied to a user that will create
          # pull requests against your projects to update dependencies. More
          # on this under the YAML snippet.
          github-token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
          # A Markdown file with a literal Markdown list of repositories
          # Scala Steward should monitor.
          repos-file: repos.md
          author-email: sbuild-ci@tototec.de
          author-name: Build Bot
